### PR TITLE
feat: added routing, made a base page

### PR DESCRIPTION
**Pull request by AnkushSharma2698**
This PR adds in: 

- routing
- Additional folder structure
- Landing Page, Homepage, and 404 Page
- Login/Register Form was added to Landing Page(Not yet hooked up to backend)

### CODE REVIEW

**Review by PENGYUXIONG — APPROVED** [review]
init frontend appearance, looks good to me. 

 how would you like to do the connection between frontend and backend?

**Comment by AnkushSharma2698** [comment]
> init frontend appearance, looks good to me.
> 
> how would you like to do the connection between frontend and backend?

I have an idea for how to do it, I can do the setup for it in this PR, but I will explain it tomorrow while we merge stuff. We would essentially treat the backend server as localhost related to the frontend

**Comment by PENGYUXIONG** [comment]
> > init frontend appearance, looks good to me.
> > how would you like to do the connection between frontend and backend?
> 
> I have an idea for how to do it, I can do the setup for it in this PR, but I will explain it tomorrow while we merge stuff. We would essentially treat the backend server as localhost related to the frontend

Ok sounds good. I will start frontend tmr then. My current tickets seems have some overlap with @JialinX . We need to sort it out soon

**Review by JialinX — APPROVED** [review]

**Review by KevinHQi — APPROVED** [review]
Looks good to me. I will see if I can help connecting it to the author backend.

**Pull request merged**
